config/routes.rb
Extractext::Application.routes.draw do
  resources :documents

  mount Resque::Server, at: '/resque'
  default_url_options :host => "www.extractext.com"
  root to: 'pages#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match '/sign-in' => 'sessions#new', as: 'sign_in'
  match '/sign-out' => 'sessions#destroy', as: 'sign_out'
  match '/syntax' => 'pages#show', :defaults => {  :id => 'syntax' }
  match '/tos' => 'pages#show', :defaults => {  :id => 'terms-of-service' }
  match '/usage' => 'pages#show', :defaults => {  :id => 'usage' }
  resource :session, only: [:create]
  match '/sign-up(/:subscription_plan_id)' => 'users#new', as: 'sign_up'
  resources :users
  resource :profile, only: [:show,:edit,:update]
  resources :password_resets, only: [:new,:create,:edit,:update]
  resource :credit_card, only: [:new,:create]
  resource :subscription, only: [:update,:destroy]
  resource :dashboard, only: [:show]
  resources :subscription_plans, only: [:index,:edit,:update] do
    collection do
      get :available
    end
  end
  resources :coupons, only: [:index,:edit,:update]
  resources :coupon_subscription_plans, only: [:create,:destroy]
  resources :webhooks, only: :create
  resources :pages

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ActiveSupport
  def show
    @timezone = current_user.timezone || "Pacific Time (US & Canada)"
    @documents = current_user.documents.order("COALESCE(remind_at, '2100-01-01') ASC").page(params[:page]).per_page(5)
  end

  def edit
    @timezones = Array.new
    timezones = TimeZone.all
    timezones.each do |tz|
      tz = tz.to_s.gsub(/\(GMT.[0-9][0-9].[0-9][0-9]\)\ /,"")
      @timezones << tz
    end
    @timezones.sort!

    if params[:oauth_token]
      request_token = session[:request_token]
      access_token_object = request_token.get_access_token(:oauth_verifier => params[:oauth_token])
      token = access_token_object.token
      secret = access_token_object.secret
      current_user.update_attributes({ :dropbox_oauth => token,:dropbox_secret => secret})
    elsif current_user.dropbox_oauth
      client = Dropbox::API::Client.new :token => current_user.dropbox_oauth, :secret => current_user.dropbox_secret
      begin
        client.ls
      rescue Exception => exc
        current_user.update_attributes({ :dropbox_oauth => nil, :dropbox_secret => nil})
        flash[:notice] = "Please Reactivate Dropbox"
        redirect_to(:controller => 'profiles',:action => 'edit')
      end
    else
      consumer = Dropbox::API::OAuth.consumer(:authorize)
      request_token = consumer.get_request_token
      @authorize_url = request_token.authorize_url(:oauth_callback => "#{request.url}")
      session[:request_token] = request_token
    end
  end

  def update
    respond_to do |format|
      if current_user.update_attributes(params[:user])
        format.html { redirect_to profile_path, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/profiles/_user_documents.haml
%br
= will_paginate @documents
- for document in @documents
  .alert.alert-info
    %table
      %tr
        %td.thumbnail
          = image_tag("/uploads/#{document.user.email}/#{document.id}.jpg",:width => "80")
        %td{:style => "padding-left:20px;width:600px;"}
          .handwritten{:style => "font-size:18px;"}
            %strong= document.title
          %h4
            - if !document.remind_at.nil?
              Reminder on
              = document.remind_at.in_time_zone("#{@timezone}").strftime("%B #{document.remind_at.in_time_zone(@timezone).day.ordinalize} at %l:%M %p")
        %td
          = link_to 'Edit', edit_document_path(document),:class => "btn btn-inverse"
        %td
          = link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger"

app/views/profiles/edit.html.haml
-title "Edit Account"
%section.well
  %header.edit_profile_header
    .handwritten{:style => "font-size:25px;"}
      = 'Edit Account'

  = simple_form_for current_user, url: profile_path, method: :put, html: { class: 'form-vertical' } do |f|
    .fieldset
      %legend= 'Account Information'
      = f.input :email, placeholder: "name@domain.com", disabled: true, hint: "You cannot change your email address."
      = f.input :timezone, :collection => @timezones,:selected => "Pacific Time (US & Canada)"
      = f.input :password, placeholder: "Please pick something strong"
      = f.input :password_confirmation, placeholder: "Please type it again."
    .fieldset
      %legend= 'SMS Settings'
      = f.input :cell_number,placeholder: "For SMS Notifications"
    .fieldset
      %legend= 'DropBox Connection'
      - if current_user.dropbox_oauth.nil?
        = link_to "Connect To Dropbox", @authorize_url,{:style=>'color:#FFFFFF;',:class => 'btn btn-info'} unless params[:oauth_token]
        %br
        %br
        Will create a folder for automatic conversions
      - else
        .alert.alert-info
          You are connected to Dropbox. Any PDFs or images in the Extractext folder will be converted.
      %br



    .fieldset
      %legend= 'Evernote Settings'
      = f.input :evernote_email,:label => "Your Evernote Email Address",placeholder: "evrnote.09226@m.evernote.com"
      = f.input :evernote_notebook,:label => "Which notebook to deliver to?",placeholder: "Inbox",hint: "Must already exist in your Evernote Account."
      = f.input :evernote_tags,:label => "Tags to Add (Comma Seperated)",placeholder: "todos, school, homework",hint: "Must already exists in your Evernote Account."
    .fieldset
      %legend= 'Kindle Settings'
      = f.input :kindle_email,:label => "Your Kindle's E-mail Address",placeholder: "mike_9962@Kindle.com",hint: "Must approve 'transcribe@extractext.com' in your Amazon Account"
      = f.input :convert_kindle, :label => "Convert to Kindle Format?",hint: ": Uncheck this if document display is undesirable on your device."
      .form-actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/profiles/show.html.haml
-title "#{current_user.email}'s Account"

.row-fluid
  .span9
    =content_tag_for(:section, current_user, class: 'well') do
      %header.user_home_header
        .handwritten{:style => "font-size:25px;"}
          = "#{current_user.email}" 
      - if current_user.subscription_content.instance_of? Array
        = render :partial => "user_documents", :locals => { :documents => @documents, :timezone => @timezone }
      - elsif current_user.subscription_content.instance_of? Fixnum
        %br
        %center
          = link_to 'No documents to display. Remember to set your timezone and reminder settings in your Account Info.',edit_profile_path,:class => "btn btn-info"
      - else
        = current_user.subscription_content
  .span3
    .well
      %ul.nav.nav-list
        %li.nav-header= "Account Settings"
        %li= link_to 'Edit Settings', edit_profile_path
        %li= link_to 'New Credit Card', new_credit_card_path
        %li= link_to 'Change Subscription', available_subscription_plans_path
        %li= link_to 'Cancel Subscription', subscription_path, method: 'delete', :confirm => 'Are you sure?'
        %li= link_to 'Sign Out', sign_out_path
    .well
      %h3 Send Attachments to:
      %br
      %h4
        = link_to "transcribe@extractext.com", "mailto:transcribe@extractext.com"
    .well
      %ul.nav.nav-list
        %strong
          %li.nav-header= "Instructions"
          %li 1. E-mail Subject will become the title of your document
          %br
          %li 2. The first line of your email body is reserved for a reminder time. See the syntax page for available time formats.
          %br
          %li 3. Anything after the first line of the body will become a note which will be used in your reminder text.
          %br
          %li 4. You will immediately receive an email with 2 file attachements; a text file including the extracted text from the image or pdf, and a searchable pdf file. This PDF file will look like your original document, but the content is searchable.
          %br
          %li 5. Extractext integrates with Evernote, can deliver notifications via text message, and optionally will deliver your document directly to your Kindle device at the reminder time. See your "Account Settings" to configure these options.