config/routes.rb
Extractext::Application.routes.draw do
  resources :documents

  mount Resque::Server, at: '/resque'
  default_url_options :host => "www.extractext.com"
  root to: 'pages#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match '/sign-in' => 'sessions#new', as: 'sign_in'
  match '/sign-out' => 'sessions#destroy', as: 'sign_out'
  match '/syntax' => 'pages#show', :defaults => {  :id => 'syntax' }
  match '/tos' => 'pages#show', :defaults => {  :id => 'terms-of-service' }
  match '/usage' => 'pages#show', :defaults => {  :id => 'usage' }
  resource :session, only: [:create]
  match '/sign-up(/:subscription_plan_id)' => 'users#new', as: 'sign_up'
  resources :users
  resource :profile, only: [:show,:edit,:update]
  resources :password_resets, only: [:new,:create,:edit,:update]
  resource :credit_card, only: [:new,:create]
  resource :subscription, only: [:update,:destroy]
  resource :dashboard, only: [:show]
  resources :subscription_plans, only: [:index,:edit,:update] do
    collection do
      get :available
    end
  end
  resources :coupons, only: [:index,:edit,:update]
  resources :coupon_subscription_plans, only: [:create,:destroy]
  resources :webhooks, only: :create
  resources :pages

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :integer(4)      not null, primary key
#  title      :string(255)
#  user_id    :integer(4)
#  content    :text
#  notes      :text
#  remind_at  :datetime
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Document < ActiveRecord::Base
  belongs_to :user
  attr_accessible  :title, :notes,:remind_at
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require "chronic"
  before_filter :require_admin, :except => [ :show,:edit ]
  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def edit
    @document  = Document.find(params[:id])
    if !@document.remind_at.nil?
      timezone = @document.user.timezone || "Pacific Time (US & Canada)"
      @remind_at =  @document.remind_at.in_time_zone("#{timezone}").strftime("%B #{@document.remind_at.day.ordinalize} at %l:%M %p")
    else
      @remind_at = ""
    end
  end

  def create
    @document = Document.new(params[:document])
    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
      render json: @document, status: :created, location: @document
    else
      render action: "new"
    end
  end

  def update
    @document = Document.find(params[:id])
    Time.zone = @document.user.timezone || "Pacific Time (US & Canada)"
    Chronic.time_class = Time.zone
    params[:document][:remind_at]  = Chronic.parse("#{params[:document][:remind_at]}")
    if @document.update_attributes(params[:document])
      redirect_to profile_path, notice: 'Document was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to profile_url
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
-title "#{current_user.email}'s Account"

.row-fluid
  .span6
    =content_tag_for(:section, current_user, class: 'well') do
      = simple_form_for(@document) do |f|
        = f.error_notification

        .form-inputs
          = f.input :title
          = f.input :notes,:input_html => {:rows => 10}
          = f.input :remind_at,:label => "Send At:",:as => :string,placeholder: "ie: next wednesday at 4:30pm",hint: "Enter in plain English",:input_html => { :value => "#{@remind_at}"}

        .form-actions
          = f.button :submit

  .span6
    .well
      .label.label-success
        Showing 1st page only
      = image_tag("/uploads/#{current_user.email}/#{@document.id}.jpg")

app/views/documents/edit.html.haml
.handwritten{:style => "font-size:22px;"}
  Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Title
    %th User
    %th Content
    %th Notes
    %th Remind at
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.title
      %td= document.user_id
      %td= document.content
      %td= document.notes
      %td= document.remind_at
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @document.title
%p
  %b User:
  = @document.user_id
%p
  %b Content:
  = @document.content
%p
  %b Notes:
  = @document.notes
%p
  %b Remind at:
  = @document.remind_at

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path