config/routes.rb
Extractext::Application.routes.draw do
  resources :documents

  mount Resque::Server, at: '/resque'
  default_url_options :host => "www.extractext.com"
  root to: 'pages#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match '/sign-in' => 'sessions#new', as: 'sign_in'
  match '/sign-out' => 'sessions#destroy', as: 'sign_out'
  match '/syntax' => 'pages#show', :defaults => {  :id => 'syntax' }
  match '/tos' => 'pages#show', :defaults => {  :id => 'terms-of-service' }
  match '/usage' => 'pages#show', :defaults => {  :id => 'usage' }
  resource :session, only: [:create]
  match '/sign-up(/:subscription_plan_id)' => 'users#new', as: 'sign_up'
  resources :users
  resource :profile, only: [:show,:edit,:update]
  resources :password_resets, only: [:new,:create,:edit,:update]
  resource :credit_card, only: [:new,:create]
  resource :subscription, only: [:update,:destroy]
  resource :dashboard, only: [:show]
  resources :subscription_plans, only: [:index,:edit,:update] do
    collection do
      get :available
    end
  end
  resources :coupons, only: [:index,:edit,:update]
  resources :coupon_subscription_plans, only: [:create,:destroy]
  resources :webhooks, only: :create
  resources :pages

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :require_admin

  def show
    @users_count = User.count
    @subscription_plans = SubscriptionPlanDecorator.decorate(SubscriptionPlan.by_amount)
  end
end

app/views/dashboards/_subscription_plan.html.haml
%li= "#{subscription_plan.name}: #{subscription_plan.users_count}, #{subscription_plan.monthly_revenue}"

app/views/dashboards/show.html.haml
-title 'Dashboard'

%section.well
  %header.dashboard_header
    %h1= 'Extractext Dashboard'
%section.span6
  .well
    %h3= 'Stats'
    %p= "Users: #{@users_count}"
    %ul
      = render partial: 'dashboards/subscription_plan', collection: @subscription_plans
%section.span6
  .well
    %ul.nav.nav-list
      %li.nav-header= "Site Administration"
      %li= link_to 'Subscription Plans', subscription_plans_path
      %li= link_to 'Coupons', coupons_path
      %li= link_to 'Users', users_path
      %li= link_to 'New Page', new_page_path
      %li= link_to 'Admin Profile', profile_path